[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = "4.5.40"
fern = "0.7.1"
log = "0.4.27"
network-direct = { version = "0.1.0", path = "../network-direct/network-direct" }
